authentic/urls.py
from django.urls import path
from .views import *

app_name = "authentic"
urlpatterns = [
    path("accounts/signup/", sign_up, name="sign_up"),
    path("accounts/login/", log_in, name="log_in"),
    path("logout/", log_out, name="log_out"),
]

bidding/urls.py
from django.urls import path

from . import views

app_name = "bidding"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

bidmaster/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse

urlpatterns = [
    path("", lambda request: redirect(reverse("authentic:log_in")), name="root_redirect"),
    path("", include("authentic.urls", namespace="authentic")),
    path("bidding/", include("bidding.urls", namespace="bidding")),
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

admin.site.site_header = "BidMaster Admin"
admin.site.site_title = "BidMaster Admin Portal"
admin.site.index_title = "Welcome to BidMaster"

bidding/models.py
import uuid
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.db import transaction
from djongo import models as djongoModels
from bson import ObjectId

class Auctioneer(models.Model):
    id = models.UUIDField(
        primary_key=True, unique=True, default=uuid.uuid4, editable=False
    )
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name="auctioneer_account",
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Auctioneer"
        verbose_name_plural = "Auctioneers"

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse("auctioneer-detail", kwargs={"pk": self.pk})


class Bidder(models.Model):
    id = models.UUIDField(
        primary_key=True, unique=True, default=uuid.uuid4, editable=False
    )
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name="bidder_account",
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Bidder"
        verbose_name_plural = "Bidders"

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse("bidder-detail", kwargs={"pk": self.pk})


class Auction(models.Model):
    class AuctionStatus(models.IntegerChoices):
        ACTIVE = 1
        CLOSED = 0

    id = models.UUIDField(
        primary_key=True, unique=True, default=uuid.uuid4, editable=False
    )
    title = models.CharField(max_length=90, null=False, blank=False)
    description = models.TextField(null=True, blank=True, default="")
    auctioneer = models.ForeignKey(
        Auctioneer, related_name="auctions", on_delete=models.CASCADE
    )
    status = models.IntegerField(
        choices=AuctionStatus.choices, default=AuctionStatus.ACTIVE
    )
    winner = models.ForeignKey(
        Bidder,
        related_name="auctions",
        on_delete=models.DO_NOTHING,
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Auction"
        verbose_name_plural = "Auctions"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("auction-detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        is_creating = self._state.adding
        if is_creating:
            self.create_auction_room()

        super().save(*args, **kwargs)

    @transaction.atomic
    def create_auction_room(self):
        auction_room = AuctionRoom(name=self.title, auction=self)
        auction_room.save()


class AuctionRoom(models.Model):
    class AuctionRoomStatus(models.IntegerChoices):
        ACTIVE = 1
        CLOSED = 0

    id = models.UUIDField(
        primary_key=True, unique=True, default=uuid.uuid4, editable=False
    )
    name = models.CharField(max_length=90, null=False, blank=False)
    status = models.IntegerField(
        choices=AuctionRoomStatus.choices, default=AuctionRoomStatus.ACTIVE
    )
    auction = models.OneToOneField(
        Auction, related_name="auction_acc", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Auction Room"
        verbose_name_plural = "Auction Rooms"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("auction-room-detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        self.name = " ".join(word.capitalize() for word in self.name.split())

        super().save(*args, **kwargs)


class AuctionRoomUser(models.Model):
    class AuctionRoomUserRole(models.TextChoices):
        ACTIONEER = "auctioneer"
        BIDDER = "bidder"

    auction_room = models.ForeignKey(AuctionRoom, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    user_role = models.CharField(
        max_length=10, choices=AuctionRoomUserRole.choices, null=False, blank=False
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Auction Room User"
        verbose_name_plural = "Auction Room Users"

    def __str__(self):
        return f"{self.auction_room.name} > {self.user.username}"

    def get_absolute_url(self):
        return reverse("auction-room-user-detail", kwargs={"pk": self.pk})


class AuctionLog(djongoModels.Model):
    id = djongoModels.ObjectIdField(primary_key=True, default=ObjectId, editable=False)
    auction_room_id = djongoModels.CharField(max_length=250)
    user_id = djongoModels.IntegerField(null=False, blank=False)
    amount = djongoModels.DecimalField(
        max_digits=11, decimal_places=2, null=False, blank=False
    )
    created_at = djongoModels.DateTimeField(auto_now_add=True)
    updated_at = djongoModels.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Auction Log"
        verbose_name_plural = "Auction Logs"
        managed = False

    def __str__(self):
        return self.id

    def get_absolute_url(self):
        return reverse("auction-log-detail", kwargs={"pk": self.pk})

bidding/views.py
import json
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import AuctionRoom, AuctionRoomUser


@login_required
def index(request):
    if request.method == "POST":
        req_room_id = request.POST.get("room_id")
        req_user_id = request.user.id

        if not req_room_id:
            messages.error(request, "Please choose a valid room.")
            return redirect(reverse("bidding:index"))

        if room_exists(req_room_id):
            verified_room_user = verify_room_user(req_room_id, req_user_id)
            if verified_room_user["verified"]:
                return redirect(reverse("bidding:room",kwargs={"room_name": verified_room_user["room_name"]}))
            else:
                messages.error(request, "Not authorized to access room.")
                return redirect(reverse("bidding:index"))
        else:
            messages.error(request, "Room does not exist.")
            return redirect(reverse("bidding:index"))

    return render(request, "index.html")


@login_required
def room(request, room_name):
    if request.method == "GET":
        req_user = request.user
        req_room_name = " ".join(word.capitalize() for word in room_name.split("_"))
        req_room_id = reverse_room_name(req_room_name)
        
        if not req_room_id["exists"]:
            messages.error(request, "Room does not exist.")
            return redirect(reverse("bidding:index"))        
        
        verify_room_and_room_user(request,req_room_id["room_id"],req_user.id)
        
        user_data = json.dumps({
            'id': req_user.id,
            'username': req_user.username,
        })
        
    return render(request, "room.html", {"room_id": req_room_id["room_id"],"room_name": room_name,"room_actual_name": req_room_name,"user_data":user_data})


# verify room exists and verify room user
def verify_room_and_room_user(request,req_room_id,req_user_id):
    if not req_room_id:
        messages.error(request, "Please choose a valid room.")
        return redirect(reverse("bidding:index"))

    if room_exists(req_room_id):
        verified_room_user = verify_room_user(req_room_id, req_user_id)
        if verified_room_user["verified"]:
            return redirect(reverse("bidding:room",kwargs={"room_name": verified_room_user["room_name"]}))
        else:
            messages.error(request, "Not authorized to access room.")
            return redirect(reverse("bidding:index"))
    else:
        messages.error(request, "Room does not exist.")
        return redirect(reverse("bidding:index"))
        
# check if room exists
def room_exists(room_id):
    try:
        return AuctionRoom.objects.filter(pk=room_id).exists()
    except:
        return False


# verify is user can access room
def verify_room_user(room_id, user_id):
    try:
        is_verified_room_user = AuctionRoomUser.objects.filter(auction_room=room_id, user=user_id)
        room_name = is_verified_room_user.first().auction_room.name
        
        return {
            "verified": is_verified_room_user.exists(),
            "room_name": room_name.lower().replace(" ", "_"),#convert room name into snake_case e.g. `My Room` to `my-room`
        }
    except:
        return {
            "verified": False,
            "room_name": None
        }

def reverse_room_name(room_name):
    try:
        room_name = AuctionRoom.objects.filter(name=room_name)        
        return {
            "exists": room_name.exists(),
            "room_id": room_name.first().id
        }
    except:
        return {
            "exists": False,
            "room_id": None
        }

bidding/templates/index.html
{% comment %} {% load django_browser_reload %} {% endcomment %}
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html class="">
  <head>
    <meta charset="utf-8" />
    <title>Bidding Rooms</title>
    {% compress css %}
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
    {% endcompress %}
  </head>
  <body class="relative flex items-center justify-center min-h-screen">
    
    <button class="absolute px-4 py-2 font-bold text-white bg-red-500 rounded top-4 right-4 hover:bg-red-700 focus:outline-none focus:shadow-outline" type="button">
      <a href="{% url 'authentic:log_out' %}">Logout</a>
    </button>      
    
    <div class="">
      <h1 class="mb-4 text-2xl font-bold text-center">What bidding room would you like to enter?</h1>
      <form class="px-4 py-6 mb-4 bg-white rounded shadow-md" action="{% url 'bidding:index' %}" method="post">
        {% csrf_token %}
        <div class="mb-4">
          <label class="block mb-2 text-sm font-bold text-gray-700" for="room-id">Room Id</label>
          <input id="room-name-input" name="room_id" class="w-full px-3 py-2 leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline" type="text" placeholder="Room Id">          
        </div>
        {% if messages %}
        <ul class="my-3">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                <p class="text-red-500 text-xs italic">{{ message }}</p>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
        <div class="flex flex-col md:flex-row md:items-center md:justify-between">
          <button id="room-name-submit" class="w-full px-4 py-2 mb-4 font-bold text-white bg-blue-500 rounded md:w-auto hover:bg-blue-700 focus:outline-none focus:shadow-outline md:mb-0" 
          type="submit">Join Room</button>
          <a class="inline-block text-sm font-bold text-center text-blue-500 hover:text-blue-800" href="javascript:void(0)">Can't find room?</a>
        </div>
      </form>
      <p class="text-xs text-center text-gray-500">&copy;2023 BidMaster. All rights reserved.</p>
    </div>


    <script>
      document.querySelector("#room-name-input").focus();
      document.querySelector("#room-name-input").onkeyup = function (e) {
        if (e.keyCode === 13) {
          // enter, return
          document.querySelector("#room-name-submit").click();
        }
      };
    </script>
  </body>
</html>

bidding/templates/room.html
{% comment %} {% load django_browser_reload %} {% endcomment %}
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{{ room_actual_name }}</title>
    {% compress css %}
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
    {% endcompress %}
  </head>
  <body class="flex flex-col items-center justify-center w-screen min-h-screen bg-gray-100 text-gray-800 p-10">

    <h2>{{ room_actual_name }}</h2>
    <!-- Component Start -->
    <div class="flex flex-col flex-grow w-full max-w-md bg-white shadow-xl rounded-lg overflow-hidden">
      <div id="bidding-log" class="flex flex-col flex-grow h-0 p-4 overflow-auto">
        <!-- Bidding messages -->
        
        <!-- Bidding messages End-->
      </div>
      
      <div class="bg-gray-300 p-4">
        <div class="flex items-center w-full justify-end">
          <span id="submitting-message" class="hidden ml-2 text-gray-500 text-sm">Placing bid...</span>
        </div>
        <div class="flex items-center justify-between w-full p-3 gap-2 border-t border-gray-300">
                <input id="bidding-message-input" class="flex items-center h-10 w-full rounded px-3 text-sm" type="text" placeholder="Type your bid amount...">
              <button type="submit" id="bidding-message-submit">
                <svg id="submit-icon" class="w-5 h-5 text-gray-500 origin-center transform rotate-90" xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20" fill="currentColor">
                  <path
                    d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z" />
                </svg>
                <svg id="loading-circle" aria-hidden="true" class="hidden h-5 w-5 mr-2 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
                  <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Component End  -->

    {{ room_name|json_script:"room-name" }}
    <script>
      const currentUser = {{ user_data|safe }};
      const currentRoomId = '{{ room_id|escapejs }}';
      
      const roomName = JSON.parse(
        document.getElementById("room-name").textContent
      );

      const submitButton = document.querySelector("#bidding-message-submit");
      const loadingCircle = document.querySelector("#loading-circle");
      const submittingMessage = document.querySelector("#submitting-message");
      const submitIcon = document.querySelector("#submit-icon");
      var submitLoading = false;

      var httpProtocol = 'http://'; 
      var wsProtocol = 'ws://';
      if (window.location.protocol === 'https:') {
          httpProtocol = 'https://';
          wsProtocol = 'wss://';
      }
      const biddingSocket = new WebSocket(
        wsProtocol + window.location.host + "/ws/bidding/" + roomName + "/"
      );
      let isOpening = true;

      biddingSocket.onmessage = function (e) {
        if(submitLoading){
          isNotSubmitting();
        }
        
        const data = JSON.parse(e.data);

        if(currentUser.username == data.username){
          //sent message
          document.querySelector("#bidding-log").innerHTML += 
          '<div class="flex w-full mt-2 space-x-3 max-w-xs ml-auto justify-end">'+
            '<div>'+
              '<div class="bg-blue-600 text-white p-3 rounded-l-lg rounded-br-lg">'+
                '<p class="text-sm">'+data.message+'</p>'+
              '</div>'+
              '<span class="text-xs text-gray-500 leading-none">'+new Date()+'</span>'+
            '</div>'+
            '<div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-300"></div>'+
          '</div>';
        } else{
          //received message
          document.querySelector("#bidding-log").innerHTML += 
          '<div class="flex w-full mt-2 space-x-3 max-w-xs">'+
            '<div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-300"></div>'+
            '<div>'+
              '<div class="bg-gray-300 p-3 rounded-r-lg rounded-bl-lg">'+
                '<p class="text-sm">'+data.message+'</p>'+
              '</div>'+
              '<span class="text-xs text-gray-500 leading-none">'+new Date()+'</span>'+
            '</div>'+
          '</div>';
        }
                
      };

      biddingSocket.onopen = function (event) {
        console.log("WebSocket connection established successfully.");
        isOpening = false;
      };

      biddingSocket.onclose = function (event) {
        setTimeout(function () {
          if (isOpening) {
            // WebSocket was closed unexpectedly but was just delayed in opening.
            console.log("WebSocket connection closed unexpectedly.");
          } else {
            // WebSocket is not in the process of opening, it's a genuine close event.
            console.log("WebSocket connection closed.");
          }
        }, 100);
      };

      biddingSocket.onerror = function (event) {
        console.error("WebSocket error:", event);
      };

      document.querySelector("#bidding-message-input").focus();
      document.querySelector("#bidding-message-input").onkeyup = function (e) {
        if (e.keyCode === 13) {
          // enter, return
          document.querySelector("#bidding-message-submit").click();
        }
      };

      document.querySelector("#bidding-message-submit").onclick = function (e) {
        const messageInputDom = document.querySelector(
          "#bidding-message-input"
        );
        const message = messageInputDom.value;
        biddingSocket.send(
          JSON.stringify({
            message: message,
            username: currentUser.username,
            room_id: currentRoomId,
          })
        );
        isSubmitting();
        messageInputDom.value = "";
      };

      function isSubmitting(){
        submitLoading = true;
        submitButton.disabled = true;
        loadingCircle.classList.remove('hidden');
        submittingMessage.classList.remove('hidden');
        submitIcon.classList.add('hidden');
      }
      function isNotSubmitting(){
        submitLoading = false;
        submitButton.disabled = false;
        loadingCircle.classList.add('hidden');
        submittingMessage.classList.add('hidden');
        submitIcon.classList.remove('hidden');
      }
    </script>
  </body>
</html>